package com.example.fitguide.dataclasses

import com.example.fitguide.R

data class ExerciseDetails(
    val title: String,
    val imageResId: Int,
    val description: String
) {
    companion object {
        private val exercises = mapOf(
            "crunch" to ExerciseDetails("Crunch", R.drawable.crunch_detalle, "El crunch es un ejercicio clásico de abdominales que trabaja principalmente el recto abdominal. Para hacerlo, te acuestas boca arriba con las rodillas dobladas y los pies planos en el suelo. Colocas las manos detrás de la cabeza (sin tirar de ella) y levantas los hombros hacia las rodillas, contrayendo los abdominales. Se recomienda hacer 3 series de 15 a 20 repeticiones cada una."),
            "escalador" to ExerciseDetails("Escalador", R.drawable.escalador_detalle, "El ejercicio \"escalador\" o \"mountain climber\" es excelente para trabajar no solo el abdomen, sino también los músculos de las piernas y los brazos, además de mejorar tu resistencia cardiovascular. Te pones en posición de plancha alta con las manos directamente debajo de los hombros. Luego, alternas llevando las rodillas hacia el pecho como si estuvieras corriendo en el lugar. Se recomienda hacer 3 series de 20 a 30 repeticiones en total (10 a 15 por pierna). "),
            "giro_ruso" to ExerciseDetails("Giro Ruso", R.drawable.giro_ruso_detalle, "El giro ruso, conocido como \"Russian twist\", es un excelente ejercicio para los oblicuos y los abdominales transversales. Siéntate en el suelo con las rodillas dobladas y los pies planos. Inclínate ligeramente hacia atrás, manteniendo la espalda recta y levanta los pies del suelo para equilibrarte sobre tu trasero. Con las manos juntas o sosteniendo un peso, gira el torso de un lado a otro tocando el suelo a cada lado con las manos o el peso. Se recomienda hacer 3 series de 15 a 20 repeticiones por lado."),
            "puente" to ExerciseDetails("Puente", R.drawable.puente_detalle, "El puente, o \"glute bridge,\" es excelente para trabajar los glúteos, el core y los isquiotibiales. Te acuestas boca arriba con las rodillas dobladas y los pies planos en el suelo, a la anchura de las caderas. Levantas las caderas hacia el techo hasta que tu cuerpo forme una línea recta desde los hombros hasta las rodillas, contrayendo los glúteos en la parte superior. Se recomienda hacer 3 series de 15 a 20 repeticiones."),
            "plancha" to ExerciseDetails("Plancha", R.drawable.plancha_detalle, "La plancha, o \"plank,\" es un excelente ejercicio para trabajar el core, los hombros y los glúteos. Te pones en posición de plancha alta con los codos directamente debajo de los hombros y el cuerpo en línea recta desde la cabeza hasta los talones. Mantén la posición, asegurándote de no dejar caer la cadera ni levantarla demasiado. Se recomienda mantener la posición durante 3 series de 20 a 30 segundos cada una."),
            // Espalda
            "dominadas" to ExerciseDetails("Dominadas", R.drawable.dominadas_detalle, "Las dominadas, o \"pull-ups,\" son ideales para trabajar la espalda, los brazos y los hombros. Agarras la barra con las palmas hacia afuera y los brazos un poco más anchos que los hombros. Luego, tiras de tu cuerpo hacia arriba hasta que la barbilla esté por encima de la barra y bajas con control. Se recomienda empezar con 3 series de 5 a 10 repeticiones"),
            "peso_muerto" to ExerciseDetails("Peso Muerto", R.drawable.peso_muerto_detalle, "El peso muerto, o \"deadlift,\" es un ejercicio integral que trabaja principalmente la espalda baja, glúteos, isquiotibiales y cuádriceps. Para hacerlo, te colocas de pie con los pies a la anchura de las caderas, las manos agarrando la barra con un agarre de pronación (palmas hacia ti). Mantienes la espalda recta y el core activado mientras levantas la barra del suelo hasta que estés completamente erguido, luego bajas con control. Se recomienda hacer 3 series de 8 a 12 repeticiones con un peso moderado."),
            "remo_invertido" to ExerciseDetails("Remo Invertido", R.drawable.remo_invertido_detalle, "El remo invertido, o \"inverted row,\" es excelente para trabajar la espalda, los bíceps y el core. Te acuestas bajo una barra colocada a la altura de la cintura (o usas una máquina de Smith). Agarras la barra con un agarre de pronación o supinación, los pies planos en el suelo, y tu cuerpo recto. Luego, tiras de tu pecho hacia la barra, manteniendo el core apretado, y bajas con control. Se recomienda hacer 3 series de 10 a 15 repeticiones."),
            "remo_polea" to ExerciseDetails("Remo con Polea", R.drawable.remo_polea_detalle, "El remo con polea, o \"cable row,\" trabaja la espalda, los bíceps y el core. Siéntate en una máquina de poleas con las rodillas ligeramente dobladas, agarra el mango con ambas manos, y tira hacia tu abdomen, manteniendo la espalda recta y los codos cerca del cuerpo. Luego, regresa con control. Se recomienda hacer 3 series de 12 a 15 repeticiones. "),
            "superman" to ExerciseDetails("Superman", R.drawable.superman_detalle, "El ejercicio \"Superman\" es ideal para trabajar la parte baja de la espalda y los glúteos. Te acuestas boca abajo en el suelo con los brazos extendidos hacia adelante. Luego, levantas simultáneamente los brazos y las piernas del suelo, contrayendo los músculos de la espalda baja y los glúteos. Mantienes la posición durante unos segundos antes de bajar con control. Se recomienda hacer 3 series de 10 a 15 repeticiones. "),
            // Hombros
            "elevaciones_frontales" to ExerciseDetails("Elevaciones Frontales", R.drawable.elevaciones_frontales_detalle, "Las elevaciones frontales, o \"front raises,\" trabajan principalmente los deltoides anteriores (hombros) y, en menor medida, los pectorales superiores. De pie, con los pies a la anchura de las caderas, agarra un par de mancuernas con las palmas hacia abajo. Levanta los brazos rectos frente a ti hasta la altura de los hombros y baja con control. Se recomienda hacer 3 series de 12 a 15 repeticiones."),
            "elevaciones_laterales" to ExerciseDetails("Elevaciones Laterales", R.drawable.elevaciones_laterales_detalle, "Las elevaciones laterales, o \"lateral raises,\" son ideales para trabajar los deltoides laterales. De pie, con los pies a la anchura de las caderas, agarra un par de mancuernas con las palmas hacia adentro. Levanta los brazos rectos hacia los lados hasta la altura de los hombros y baja con control. Se recomienda hacer 3 series de 12 a 15 repeticiones."),
            "press_barra" to ExerciseDetails("Press con Barra", R.drawable.press_barra_detalle, "El press con barra, o \"barbell shoulder press,\" es fantástico para trabajar los deltoides, trapecios y tríceps. De pie, con los pies a la anchura de las caderas, agarra la barra con las manos un poco más anchas que los hombros. Empieza con la barra a la altura de los hombros y presiona hacia arriba hasta que los brazos estén extendidos. Luego, baja con control. Se recomienda hacer 3 series de 8 a 12 repeticiones."),
            "press_mancuerna" to ExerciseDetails("Press con Mancuerna", R.drawable.press_mancuernas_detalle, "El press con mancuerna, o \"dumbbell shoulder press,\" es ideal para trabajar los deltoides, trapecios y tríceps. Siéntate o párate con los pies a la anchura de las caderas, agarra una mancuerna en cada mano a la altura de los hombros con las palmas hacia adelante. Empuja las mancuernas hacia arriba hasta que los brazos estén completamente extendidos y luego baja con control. Se recomienda hacer 3 series de 8 a 12 repeticiones."),
            "remo_vertical" to ExerciseDetails("Remo Vertical", R.drawable.remo_vertical_detalle, "El remo vertical, o \"upright row,\" es un ejercicio fantástico para trabajar los deltoides, trapecios y los músculos de la parte superior de la espalda. De pie, con los pies a la anchura de las caderas, agarra una barra con las manos a la anchura de los hombros y las palmas hacia adentro. Levanta la barra hacia la barbilla, manteniendo los codos más altos que las manos, y baja con control. Se recomienda hacer 3 series de 10 a 15 repeticiones."),
            // Pecho
            "apertura_mancuerna" to ExerciseDetails("Apertura con Mancuernas", R.drawable.apertura_mancuernas_detalle, "La apertura con mancuernas, o \"dumbbell flyes,\" es fantástica para trabajar el pecho, especialmente los músculos pectorales mayores. Acuéstate en un banco plano con una mancuerna en cada mano. Levanta las mancuernas directamente sobre tu pecho con los brazos extendidos pero con una ligera flexión en los codos. Abre los brazos hacia los lados en un movimiento de arco hasta que sientas un buen estiramiento en el pecho, y luego vuelve a juntar las mancuernas sobre tu pecho. Se recomienda hacer 3 series de 10 a 15 repeticiones."),
            "cruce_polea" to ExerciseDetails("Cruce con Poleas", R.drawable.cruce_poleas_detalle, "El cruce con polea, o \"cable crossover,\" es excelente para trabajar los músculos pectorales. Te colocas en medio de dos poleas ajustables, agarras las manijas con las palmas hacia abajo y das un paso hacia adelante, inclinándote ligeramente al frente. Tirando de las manijas hacia abajo y delante de ti, juntas las manos en la parte baja del movimiento, cruzando ligeramente las muñecas. Luego, regresas con control a la posición inicial. Se recomienda hacer 3 series de 12 a 15 repeticiones."),
            "flexiones" to ExerciseDetails("Flexiones", R.drawable.flexiones_detalle, "Las flexiones, o \"push-ups,\" son un ejercicio clásico que trabaja el pecho, los tríceps y los deltoides. Empiezas en una posición de plancha alta con las manos un poco más anchas que los hombros. Bajas el cuerpo manteniendo una línea recta desde la cabeza hasta los talones, hasta que el pecho esté cerca del suelo. Luego, empujas hacia arriba para volver a la posición inicial. Se recomienda hacer 3 series de 10 a 20 repeticiones."),
            "press_banca" to ExerciseDetails("Press en Banca", R.drawable.press_banca_detalle, "El press de banca, o \"bench press,\" es uno de los ejercicios más efectivos para trabajar los músculos del pecho, además de los tríceps y los hombros. Acuéstate en un banco plano con los pies firmemente en el suelo y la barra a la altura de los ojos. Agarra la barra con las manos un poco más anchas que los hombros, baja la barra hacia el pecho mientras mantienes los codos a unos 45 grados del cuerpo, y empuja hacia arriba hasta extender completamente los brazos. Se recomienda hacer 3 series de 8 a 12 repeticiones."),
            "press_inclinado_mancuernas" to ExerciseDetails("Press Inclinado", R.drawable.press_inclinado_mancuernas_detalle, "El press inclinado con mancuernas, o \"incline dumbbell press,\" es excelente para trabajar la parte superior del pecho, así como los deltoides y tríceps. Acuéstate en un banco inclinado (a unos 30-45 grados) con una mancuerna en cada mano. Con las palmas hacia adelante y los codos en ángulo de 90 grados, presiona las mancuernas hacia arriba hasta que los brazos estén extendidos. Luego, baja con control hasta la posición inicial. Se recomienda hacer 3 series de 8 a 12 repeticiones."),
            // Piernas
            "extension_rodillas" to ExerciseDetails("Extensión de Rodillas", R.drawable.extension_rodillas_detalle, "La extensión de rodillas, o \"leg extension,\" es un ejercicio eficaz para trabajar los cuádriceps. Siéntate en una máquina de extensión de piernas con las espinillas contra los rodillos. Ajusta la máquina para que las rodillas estén alineadas con el eje de rotación de la máquina. Levanta las piernas extendiendo las rodillas hasta que estén casi rectas y luego baja con control. Se recomienda hacer  3 series de 12 a 15 repeticiones."),
            "prensa_piernas" to ExerciseDetails("Prensa de Piernas", R.drawable.prensa_piernas_detalle, "La prensa de piernas, o \"leg press,\" es excelente para trabajar los cuádriceps, glúteos y los isquiotibiales. Te sientas en la máquina de prensa de piernas y colocas los pies en la plataforma a la anchura de los hombros. Empuja la plataforma con las piernas hasta extender casi por completo las rodillas y luego baja con control, manteniendo una ligera flexión en las rodillas. Se recomienda hacer 3 series de 10 a 15 repeticiones."),
            "sentadillas" to ExerciseDetails("Sentadillas", R.drawable.sentadillas_detalles, "Las sentadillas, o \"squats,\" son uno de los ejercicios más efectivos para trabajar los músculos de las piernas y los glúteos. Se enfocan principalmente en los cuádriceps, los glúteos, los isquiotibiales y el core. Para hacer una sentadilla, te pones de pie con los pies a la anchura de los hombros y bajas las caderas como si te fueras a sentar en una silla, manteniendo la espalda recta y el pecho levantado. Luego, te empujas hacia arriba hasta la posición inicial. Se recomienda 3 series de 12 a 15 repeticiones."),
            "step_up" to ExerciseDetails("Step-Up", R.drawable.step_up_detalle, "Los step-ups son un ejercicio fantástico para trabajar los cuádriceps, glúteos e isquiotibiales, además de mejorar el equilibrio. Para hacer step-ups, necesitas un banco o una plataforma elevada. De pie, con los pies separados a la anchura de las caderas, subes un pie al banco y luego te impulsas hacia arriba, trayendo la otra pierna hasta que ambos pies estén en la plataforma. Luego, bajas de una pierna a la vez. Se recomienda hacer 3 series de 10 a 12 repeticiones por pierna."),
            "zancadas" to ExerciseDetails("Zancadas", R.drawable.zancadas_detalle, "Las zancadas, o \"lunges,\" son excelentes para trabajar los cuádriceps, glúteos, isquiotibiales y el core. Para hacer una zancada, das un paso hacia adelante con una pierna, bajando las caderas hasta que ambas rodillas estén dobladas en un ángulo de 90 grados. Luego, te empujas hacia arriba para volver a la posición inicial y repites con la otra pierna. Se recomienda hacer 3 series de 10 a 12 repeticiones por pierna.")
        )

        fun getExerciseDetails(exerciseDetail: String?): ExerciseDetails? {
            return exercises[exerciseDetail]
        }
    }
}
